import React, { useEffect, useState } from 'react';
import { fetchAgentFeed, FeedPost } from '../api/client';
import { Rss, Clock, ExternalLink, Award, Sparkles, MessageSquareQuote, ShieldAlert } from 'lucide-react';
import toast from 'react-hot-toast';

export const LiveFeed: React.FC = () => {
  const [posts, setPosts] = useState<FeedPost[]>([]);
  const [loading, setLoading] = useState<boolean>(true);

  const loadFeed = async () => {
    try {
      setLoading(true);
      const res = await fetchAgentFeed();
      setPosts(res.posts || []);
    } catch (err) {
      toast.error('Failed to load live feed');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadFeed();
  }, []);

  if (loading) {
    return (
      <div className="py-20 flex flex-col items-center justify-center space-y-4">
        <Sparkles className="w-10 h-10 text-cyan-400 animate-spin" />
        <p className="text-sm font-mono text-slate-400">Loading SignalForge Live Feed...</p>
      </div>
    );
  }

  return (
    <div className="space-y-8 py-6 max-w-4xl mx-auto">
      
      {/* Feed Header */}
      <div className="glass-panel p-6 rounded-2xl border border-slate-800 flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-2">
            <Rss className="w-6 h-6 text-cyan-400" />
            <span>Autonomous Intelligence Feed</span>
          </h1>
          <p className="text-xs text-slate-400 font-mono mt-1">
            Real-time infrastructure briefs generated by SignalForge AI
          </p>
        </div>
        <span className="px-3 py-1 rounded-full bg-cyan-500/10 text-cyan-400 text-xs font-mono border border-cyan-500/20">
          {posts.length} Published Briefs
        </span>
      </div>

      {/* Feed Posts List */}
      {posts.length === 0 ? (
        <div className="glass-panel p-12 rounded-2xl text-center space-y-4 border border-slate-800">
          <ShieldAlert className="w-12 h-12 text-slate-600 mx-auto" />
          <h3 className="text-lg font-bold text-white">No Published Briefs Yet</h3>
          <p className="text-sm text-slate-400 max-w-md mx-auto">
            The autonomous scheduler will publish briefs automatically as high-scoring topics are discovered.
          </p>
        </div>
      ) : (
        <div className="space-y-6">
          {posts.map((post) => (
            <article key={post.id} className="glass-card p-6 sm:p-8 rounded-2xl space-y-6">
              
              {/* Card Header: Timestamp & Publishing Score */}
              <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800/80 pb-4">
                <div className="flex items-center gap-2 text-xs font-mono text-slate-400">
                  <Clock className="w-4 h-4 text-cyan-400" />
                  <span>{new Date(post.createdAt).toUTCString()}</span>
                </div>

                <div className="flex items-center gap-1.5 px-3 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/30 text-indigo-300 text-xs font-mono">
                  <Award className="w-3.5 h-3.5 text-indigo-400" />
                  <span>Publishing Score: 85+ / 100</span>
                </div>
              </div>

              {/* Post Content Display */}
              <div className="prose prose-invert max-w-none text-slate-200 text-sm sm:text-base leading-relaxed whitespace-pre-line font-sans">
                {post.text}
              </div>

              {/* Editorial Rationale Box */}
              <div className="p-4 rounded-xl bg-slate-900/80 border border-cyan-500/20 space-y-1.5">
                <div className="flex items-center gap-2 text-xs font-semibold text-cyan-400 uppercase tracking-wider font-mono">
                  <MessageSquareQuote className="w-4 h-4 text-cyan-400" />
                  <span>Editorial Rationale</span>
                </div>
                <p className="text-xs sm:text-sm text-slate-300 italic">
                  "{post.rationale}"
                </p>
              </div>

              {/* Information Sources */}
              {post.sources && post.sources.length > 0 && (
                <div className="flex flex-wrap items-center gap-3 pt-2 text-xs font-mono">
                  <span className="text-slate-500 uppercase tracking-wider text-[10px]">Sources:</span>
                  {post.sources.map((src, i) => (
                    <a
                      key={i}
                      href={src.url || '#'}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-1.5 px-3 py-1 rounded-md bg-slate-800/80 hover:bg-slate-700/80 text-cyan-300 border border-slate-700 transition-colors"
                    >
                      <span>{src.title || 'Live Tech Source'}</span>
                      <ExternalLink className="w-3 h-3 text-cyan-400" />
                    </a>
                  ))}
                </div>
              )}

            </article>
          ))}
        </div>
      )}

    </div>
  );
};
